### PR TITLE
Baseplate and mounting lugs

### PR DESCRIPTION
**Pull request by GraceAnyelwisye**
added mounting hole in microscope parameter and microscope main body

### CODE REVIEW

**Comment by rwb27** [comment]
Thanks, that looks great.  I would make a couple of changes though:
1. delete the two echo() lines from main_body.scad
2. make sure the code is indented correctly
3. add a comment explaining that these are the holes to mount onto the baseplate
4. remove the line above the second for() block (it isn't needed any more).  The one that starts ``eflect([1,0,0]) translate([20,z_nut_y+2,0]) cylinder(r=4/2*1.1,h=999,center=true); ``

If you can add that and commit it, I will be able to pull the changes through.

**Comment by GraceAnyelwisye** [comment]
added holes to mount onto baseplate

**Comment by rwb27** [comment]
Great - I've just checked the other files, and it would be good to have only one SCAD file for the baseplate (currently there is baseplate and baseplate_minimal; do you know which one is correct).  If you could put the right one in the openscad folder directly (not in the base_plate folder), and call it baseplate.scad, that would be great.  The STL file can be included in the "stl" folder if you like, or removed.  The base_plate folder should be removed too, just to keep things tidy.

**Comment by GraceAnyelwisye** [comment]
Okay.


Regards,
Eng. Grace Anyelwisye,
Researcher,
STICLab LTD,
P. O. Box 70583,
DAR ES SAAAM - TANZANIA.
Mob: +255712238963
Skype: Grace Anyelwisye
WebSite: www.sticlab.co.tz

**Comment by rwb27** [comment]
Looks good to me - I'll merge it now :)

**Pull request merged**
